In [1]:
import torch
import torch.nn as nn

In [ ]:
# input
torch.manual_seed(42) # to get the same output every run
inputs = torch.tensor([1.0, 2.0, 3.0])

In [ ]:
neuron = nn.Linear(in_features=3, out_features=1) # Linear Activation Function

In [21]:
output = neuron(inputs)

In [22]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [23]:
# verify - using formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [24]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)